apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: landing-page
build:
  artifacts:
    - image: landing-page
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/web.yaml
