apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: iteam-next-site
build:
  artifacts:
    - image: iteam-next-site
      context: client
deploy:
  kubectl:
    manifests:
      - k8s/web.yaml
